---
- name: Install Apache HTTP server
  apt:
    name: apache2
    state: present
    update_cache: yes
  tags: install

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
  tags: service

- name: Configure firewall to allow HTTP traffic
  ufw:
    rule: allow
    name: 'Apache'
    port: 80
    proto: tcp
    state: enabled
  tags: firewall
